### ISSUE TITLE
pwd reports incorrectly?

### ISSUE THREAD

**Issue by for-coursera** [ap/vim-readdir#2]
Here's a screenshot showing the bottom of readdir's window:

![readdir-screenshot](http://i.imgur.com/QLF3fe7.png)

As you may see, while readdir reports one directory in the status line (this one is correct, `/Users/s/.config/notes`), vim, if asked `:pwd` or `:echo getcwd()`, returns the other directory as a result (this one, `/Users/s/.config`, is incorrect since it's a parent to the working directory).

Can it be fixed so that vim's working directory would be in line with the one opened in readdir?

Thanks :).

**Comment by ap** [comment]
This is easy to do… in any one of 130 different ways. The hard part is to deciding which of those is the right one. E.g. should it do `:chdir` or `:lchdir`? How is it supposed to interact with [`'autochdir'`](http://vimdoc.sourceforge.net/htmldoc/options.html#'autochdir') or autocommands that take over the current working directory – should it re-change to the displayed directory every time the buffer is entered, or just change once when the user opens a directory?

Currently it does nothing, on purpose, because that’s the simplest design.

So a good start would be for you to tell me how you manage the current directory in Vim, and what exactly you expect vim-readdir to do for you.

**Comment by for-coursera** [comment]
For me, `:lchdir` seems like a reasonable choice. But I bet you may find some arguments for `:chdir`, too :).

Also, it seems logical to me that whenever a user returns to readdir's window, its current directory -- if changed -- will be set to the one readdir's actually browsing.

Reason I expect vim to report the same working directory as readdir is showing is simple -- because I may want to interact with that directory from vim. Differences in what you see on a screen and what you get from vim will make that quite probematic :).

**Comment by ap** [comment]
> I may want to interact with that directory from vim.

Thanks for pointing that out. I’m not sure what blindness struck me but I somehow failed to realise that. Everything is obvious after that.

Now implemented and I’ll soon upload to vim.org also. Share and enjoy.
