### ISSUE TITLE
Way to use netrw's gx with vim-readdir

### ISSUE THREAD

**Issue by gibfahn** [ap/vim-readdir#8]
Loving this plugin's functionality, the only thing I miss from netrw is the `gx` command to open a URL.

Do you know if there's a way to just have that function, but still use readdir for everything else? I've tried playing with the variables in the [netrw docs](http://vimdoc.sourceforge.net/htmldoc/pi_netrw.html), but I haven't found anything that works.

If this is just not possible, feel free to close directly.

**Comment by ap** [comment]
I don’t know anything about `gx` so I tried it out briefly and also looked at the docs – which aren’t really helpful here.

So: it seems to have a lot of pluggable functionality for doing custom things depending on the type of file… and maybe URL scheme or something? How much of that do you use?

If you just need the most basic functionality of opening HTTP links, it should be quite easy to emulate just that bit in a handful of lines of code.

If you need the full-bore insanity that Netrw theoretically allows, then I’d say you’re better off sticking with Netrw.

**Comment by gibfahn** [comment]
>How much of that do you use?

Just the HTTP link opening part. I wrote something basic that works for the most part, but I was thinking that it would be nice to use the built-in one if possible. Not the end of the world though.

**Comment by ap** [comment]
I suppose the question is whether it’s possible to keep Netrw from trying to handle
`:e somedirectory`

For me, a major reason I dislike Netrw is just how huge and complex it is, meaning I don’t want it loaded at all. So I’ve only looked into how to suppress it entirely. And since it can’t interfere with Readdir when it’s not even loaded, I just never had any need to look into how to make the two plugins coexist.

But if you want Netrw’s actual `gx` then of course you do need it loaded, so you do need to keep them from interfering with each other. Maybe it’s even easy. I just never looked into it.

**Comment by gibfahn** [comment]
Thanks for the details, if there's not an obvious way to do it I guess reimplementing it is the easiest method, I'll stick with that.

I agree that it's not worth loading the whole thing just for this one mapping.
